import { Link, useOutletContext } from 'react-router-dom';
import { ArrowRight, Check, Clock3, Hammer, MapPin, Ruler, Sparkles } from 'lucide-react';
import useFetch from '../hooks/useFetch';
import { projectApi, serviceApi, testimonialApi } from '../api/services';
import SectionTitle from '../components/SectionTitle';
import ContactForm from '../components/ContactForm';
const localProjects = [
  { title: 'Modular Kitchen Cabinet', category: 'kitchen', image: '/images/kitchen-cabinet.jpeg', desc: 'Functional kitchen cabinetry with a warm wood finish.' },
  { title: 'Dressing Mirror Unit', category: 'wardrobe', image: '/images/dressing-mirror.jpeg', desc: 'Custom storage and mirror unit designed for the room.' },
  { title: 'Office Interior Design', category: 'office', image: '/images/office-interior.jpeg', desc: 'Practical woodwork for workspaces and commercial interiors.' },
];
const localServices = [
  { name: 'Modular Kitchens', description: 'Custom modular kitchen design and installation.', icon: 'Kitchen' },
  { name: 'Wardrobes', description: 'Built-in and storage-focused wardrobe solutions.', icon: 'Wardrobe' },
  { name: 'Custom Furniture', description: 'Beds, TV units, study tables and made-to-order furniture.', icon: 'Furniture' },
  { name: 'Full Home Interiors', description: 'End-to-end carpentry for homes and apartments.', icon: 'Home' },
];
export default function Home() {
  const { lang } = useOutletContext();
  const { data: projects } = useFetch(() => projectApi.list({ featured: true, limit: 3 }), []);
  const { data: services } = useFetch(() => serviceApi.list(), []);
  const { data: reviews } = useFetch(() => testimonialApi.list(), []);
  const featured = projects?.length ? projects : localProjects;
  const serviceList = services?.length ? services : localServices;
  const t = lang === 'ta';
  return <>
    <section className="hero-section"><div className="hero-photo"/><div className="hero-overlay"/><div className="container hero-content"><div className="hero-copy"><span className="eyebrow">{t ? 'கோயம்புத்தூர் • 1990 முதல்' : 'COIMBATORE • SINCE 1990'}</span><h1>{t ? <>கைவினை மரவேலைகள் & <span>இன்டீரியர் தீர்வுகள்.</span></> : <>Handmade woodwork & <span>interior solutions.</span></>}</h1><p>{t ? 'மாடுலர் கிச்சன், வார்ட்ரோப், ஃபர்னிச்சர், கதவுகள் மற்றும் வீட்டு இன்டீரியர் வேலைகள்.' : 'Custom kitchens, wardrobes, furniture, doors and practical home interiors — crafted locally in Coimbatore.'}</p><div className="hero-actions"><Link className="btn" to="/gallery">{t ? 'வேலைப்பாடுகளை பார்க்க' : 'View our work'} <ArrowRight size={17}/></Link><Link className="btn btn-light" to="/contact">{t ? 'திட்டம் பேசலாம்' : 'Discuss a project'}</Link></div><div className="hero-meta"><span><MapPin size={15}/> Perur, Coimbatore</span><span><Clock3 size={15}/> 35+ years of practice</span></div></div></div></section>
    <section className="trust-strip"><div className="container trust-grid"><div><strong>35+</strong><span>Years of practice</span></div><div><strong>Local</strong><span>Coimbatore projects</span></div><div><strong>Direct</strong><span>Owner-led supervision</span></div><div><strong>Custom</strong><span>Made for your space</span></div></div></section>
    <section className="section"><div className="container story-grid"><div><SectionTitle eyebrow={t ? 'எங்கள் கதை' : 'Our story'} title={t ? 'மரவேலை ஒரு குடும்பப் பாரம்பரியம்.' : 'A family trade, built around wood.'}/><p className="lead-copy">{t ? 'பாஸ்கரன் K T 1990 முதல் கோயம்புத்தூரில் தனிப்பட்ட முறையில் தச்சு மற்றும் இன்டீரியர் வேலைகளை செய்து வருகிறார். பாரம்பரிய கைவினை அனுபவத்தை இன்றைய வீட்டு தேவைகளுடன் இணைப்பதே அணுகுமுறை.' : 'Wooden Lines is built around the hands-on experience of Baskaran K T, who has independently handled carpentry and interior work across Coimbatore since 1990. The approach is simple: combine traditional workmanship with the practical needs of today’s homes and businesses.'}</p><p>From measurements and layout to fitting and finishing, projects are handled closely on site. The result is intended to be useful, durable and made around the space you actually have.</p><Link className="under-link" to="/contact">{t ? 'எங்களை தொடர்பு கொள்ளுங்கள்' : 'Talk to us'} <ArrowRight size={16}/></Link></div><div className="story-card"><div className="story-number">35<span>+</span></div><h3>{t ? 'பாரம்பரிய அனுபவம்' : 'Years of traditional practice'}</h3><p>{t ? '1990 முதல் மரவேலை மற்றும் இன்டீரியர் பணிகள்.' : 'A locally rooted carpentry practice since 1990.'}</p><div className="story-list"><span><Check size={15}/> Accurate site measurements</span><span><Check size={15}/> Custom layouts</span><span><Check size={15}/> On-site fitting</span></div></div></div></section>
    <section className="section section-tint"><div className="container"><SectionTitle eyebrow={t ? 'சேவைகள்' : 'What we do'} title={t ? 'உங்கள் இடத்திற்கான வேலை.' : 'Woodwork that fits the way you live.'} text={t ? 'வீடு முதல் அலுவலகம் வரை தேவைக்கேற்ப மரவேலை.' : 'From individual pieces to complete interior carpentry, the API-backed service catalogue can be managed from the admin dashboard.'} center/><div className="service-grid">{serviceList.map((s, i) => <div className="service-card" key={s._id || s.name}><span className="service-icon">{i === 0 ? <Sparkles/> : i === 1 ? <Ruler/> : i === 2 ? <Hammer/> : <Check/>}</span><span className="service-num">0{i + 1}</span><h3>{s.name}</h3><p>{s.description}</p>{s.startingPrice && <small>From ₹{Number(s.startingPrice).toLocaleString('en-IN')} {s.priceUnit === 'per_sqft' ? '/ sq.ft' : s.priceUnit === 'per_piece' ? '/ piece' : ''}</small>}</div>)}</div><div className="center-action"><Link className="btn btn-outline-dark" to="/services">See all services <ArrowRight size={16}/></Link></div></div></section>
    <section className="section"><div className="container"><div className="split-heading"><SectionTitle eyebrow={t ? 'தேர்ந்தெடுக்கப்பட்ட வேலைகள்' : 'Selected work'} title={t ? 'நாங்கள் செய்த வேலைகள்.' : 'A few pieces from the portfolio.'}/><Link className="under-link" to="/gallery">View full gallery <ArrowRight size={16}/></Link></div><div className="project-grid home-projects">{featured.map((p, i) => <Link to={p.slug ? `/projects/${p.slug}` : '/gallery'} className="project-card" key={p._id || p.title}><div className="project-image"><img src={p.coverImage || p.images?.[0] || p.image || localProjects[i % localProjects.length].image} alt={p.title}/><span>{p.category}</span></div><div className="project-copy"><h3>{p.title}</h3><p>{p.description || p.desc}</p><ArrowRight size={17}/></div></Link>)}</div></div></section>
    <section className="section testimonial-band"><div className="container"><SectionTitle eyebrow="Client words" title="What people say" center/>{reviews?.length ? <div className="review-grid">{reviews.slice(0, 3).map((r) => <div className="review-card" key={r._id}><div className="stars">{'★'.repeat(r.rating)}<span>{'★'.repeat(5-r.rating)}</span></div><p>“{r.message}”</p><strong>{r.clientName}</strong><small>{r.location}</small></div>)}</div> : <div className="review-placeholder"><p>Approved client reviews will appear here once they are added through the backend.</p><Link to="/contact" className="under-link">Leave an enquiry instead <ArrowRight size={16}/></Link></div>}</div></section>
    <section className="section contact-section"><div className="container contact-grid"><div><SectionTitle eyebrow={t ? 'தொடர்பு' : 'Start a conversation'} title={t ? 'உங்கள் இடத்தைப் பற்றி பேசலாம்.' : 'Tell us what you are building.'} text={t ? 'தேவையை சொல்லுங்கள். தள அளவீடு மற்றும் வேலை விவரங்களை அடுத்ததாக பேசலாம்.' : 'Share the kind of work, location and rough requirements. The enquiry goes directly to the backend lead-management system.'}/><div className="contact-details"><span><MapPin/>11, Arunachalam Layout, Aandipalayam, Perur, Coimbatore — 641010</span><a href="tel:+919842234749"><Clock3/>+91 98422 34749</a></div></div><div className="contact-panel"><ContactForm/></div></div></section>
  </>;
}
